### ISSUE TITLE
Update blocks-markdown dependencies.

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#1018]
Both have major version updates with breaking changes:
- [x] `react-markdown`
- [x] `remark-gfm`. 

Also update:
- [x] `react-syntax-highlighter`.

**Comment by sah-memela** [comment]
Markdown

<img width="1440" alt="1Screenshot 2021-12-09 at 19 10 13" src="https://user-images.githubusercontent.com/8709039/145535766-ad884d1d-48c9-48ea-8b6e-f231c413ce90.png">

MarkdownWithCode

<img width="1440" alt="2Screenshot 2021-12-09 at 19 09 09" src="https://user-images.githubusercontent.com/8709039/145535803-48185b9c-0eee-4fa0-8337-536d3935c99f.png">

DangerousMarkdown

<img width="1440" alt="3Screenshot 2021-12-09 at 19 07 28" src="https://user-images.githubusercontent.com/8709039/145535829-03463f8f-fec5-47d4-b666-6e0e29fac48e.png">
