### ISSUE TITLE
Feature Request: Lowdefy Connection to read data from local files (.json/.yaml/etc)

### ISSUE THREAD

**Issue by djpbessems** [lowdefy/lowdefy#1062]
As discussed on Discord; it would be useful to be able to read data from local files through a Lowdefy Connection.

Right now this would require for instance a custom JsAction using `fetch`, or an external REST API served (think Fastify).

In an ideal situation, the local file would even be watched for changes (if the file is modified by outside processes).

**Comment by Gervwyk** [comment]
Hi @djpbessems 
Using the `_ref` operator would be the preferred approach with this, also not sure how nextjs would handle this, especially with various hosting providers.
