### ISSUE TITLE
Deployment via Node.js: "/public" folder not serving expected resources (i.e., svg, jpg, etc.)

### ISSUE THREAD

**Issue by ralphtee** [lowdefy/lowdefy#1069]
### Issue Description

Lowdefy deployed via Node.js: when requesting for non-HTML resources from the public folder (e.g., svg, jpg, etc.), it returned HTML instead.

### Steps to Reproduce

1) I followed Step 1 to Step 8 in [Deploy with Node.js](https://docs.lowdefy.com/node-server)

2) Pointed Chrome browser at http://localhost:3000. The screen shot is as below.

![cap1](https://user-images.githubusercontent.com/22031088/150715909-af40e48b-1c41-4954-8262-657c2b463b89.JPG)

3) Inspection with _curl_ returned the result below (excerpt)

![cap2](https://user-images.githubusercontent.com/22031088/150715929-2141544a-4321-4331-8ce7-89a2f05c9517.JPG)

### Lowdefy Version

lowdefy: 3.23.2
lowdefy/server-node: 3.23.2

### More Info

This problem does not affect the Lowdefy Development Server (i.e., "lowdefy dev")

**Comment by pietryszak** [comment]
@ralphtee what is solution for that?

**Comment by Gervwyk** [comment]
Hi @pietryszak, Are you also experiencing this issue? If so, what version?

**Comment by pietryszak** [comment]
I found a solution. I just need to download files from branch v3, and put thems to public folder.

I use 'git clone --depth 2 --branch v3 https://github.com/lowdefy/lowdefy.git' and them 'cp -r ~git_clone/lowdefy/packages/shell/src/public [destination of lowdefy main folder] '
