### ISSUE TITLE
Version 4 failing tests

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#1086]
The following tests are failing/missing in V4.

- [x] `@lowdefy/operators-js` failing tests
- [x] `@lowdefy/operators-nunjucks` failing tests
- [x] `@lowdefy/api` `callRequest` tests failing
- [x] `@lowdefy/build` failing tests
- [x] `@lowdefy/cli` runCommand tests failing
- [x] `@lowdefy/docs` color transformer test
- [x] `@lowdefy/engine` failing tests
- [ ] `@lowdefy/blocks-antd` failing tests
- [ ] `@lowdefy/blocks-basic` failing tests
- [ ] `@lowdefy/blocks-color-selectors` failing tests
- [ ] `@lowdefy/blocks-echarts` failing tests
- [ ] `@lowdefy/blocks-loaders` failing tests
- [ ] `@lowdefy/blocks-markdown` failing tests
- [x] `@lowdefy/cli` improve coverage where possible
- [x] `@lowdefy/build` plugin import missing tests
- [ ] `@lowdefy/api` `createApiContext` tests missing
- [ ] Operator NodeParser and WebParser integration tests missing

**Comment by JohannMoller** [comment]
Operator tests:
Test NodeParser and WebParser integration for all operators
