### ISSUE TITLE
404 on link to docs

### ISSUE THREAD

**Issue by pleabargain** [lowdefy/lowdefy#1289]
#### Describe the bug

On this page
https://docs.lowdefy.com/ControlledList
the link to edit the github repo is a 404
https://github.com/lowdefy/lowdefy/blob/main/packages/docs/blocks/ControlledList/ControlledList.yaml
#### To Reproduce
go to https://docs.lowdefy.com/ControlledList
click on 
[Edit this page on Github](https://github.com/lowdefy/lowdefy/blob/main/packages/docs/blocks/ControlledList/ControlledList.yaml)

#### Lowdefy Version
Lowdefy app version 3.23.3.

**Comment by iron3oxide** [comment]
I think this can be closed since #1294 was merged.
