### ISSUE TITLE
RadioSelector in vertical order

### ISSUE THREAD

**Issue by nbnkhanh** [lowdefy/lowdefy#1301]
Hello, we saw an issue that deals with rendering the RadioSelector buttons in vertical order here: https://github.com/lowdefy/lowdefy/issues/808

But we cannot find that vertical option on the main documentation page:
https://docs.lowdefy.com/RadioSelector

We are using version 3.23.3

**Comment by Gervwyk** [comment]
Hi @nbnkhanh 

This is a v4 implementation as tagged #808, so will only work for config >v4.
