### ISSUE TITLE
Link does not work on OpenID Connect documentation page

### ISSUE THREAD

**Issue by nbnkhanh** [lowdefy/lowdefy#1302]
#### Describe the bug

On the OpenID Connection section of the Lowdefy documentation page (https://docs.lowdefy.com/openid-connect), on the line "Details to configure specific OpenID Connect providers are given [here]", the here hyperlink leads us to 404.

![image](https://user-images.githubusercontent.com/44111901/180329473-c6776aaa-b4df-42cc-96aa-d590b06efd4f.png)

**Comment by iron3oxide** [comment]
I can't find any page that could have been the intended target of this link, so I'd say the details for that aren't written up yet. Still good to have this issue as a reminder though I guess.

**Comment by Gervwyk** [comment]
Auth docs has been updated. See https://docs.lowdefy.com/OpenIDConnectProvider et al.
