### ISSUE TITLE
Defined "pageId" setting for MenuGroup menu item produces error in console

### ISSUE THREAD

**Issue by kemeris2000** [lowdefy/lowdefy#1607]
#### Describe the bug

Defined "pageId" setting for MenuGroup menu item produce error in console while "pageId" setting itself is functioning as expected.

#### To Reproduce

<pre><code>
menus:
  - id: default
    links:
      - id: b4a1d739-3595-412e-859f-215246cc32ab1
        type: MenuLink
        pageId: home
        properties:
          title: Home
          icon: HomeOutlined
      - <b>id: 08626737-6223-4511-882e-3fc86496b0f1</b>
        type: MenuGroup
        <b>pageId: service_list</b>
        properties:
          title: Paslaugos
          icon: MdSettingsSuggest
</code></pre>

#### Screenshots

<pre><code>
12:07:53 ⚠ Schema Error
must NOT have additional properties
- menus
 - [0:default:_ERROR_MISSING_TYPE_].links
  - <b>[1:08626737-6223-4511-882e-3fc86496b0f1:MenuGroup]</b>
</code></pre>

#### Lowdefy Version

4.0.0-rc.9

**Comment by Gervwyk** [comment]
Hi @kemeris2000 This is not a bug, it is a configuration error, because MenuGroup does not take pageId as a property. MenuGroup is used to group MenuLinks, which does have a pageId property. The error here is to help the developer detect configuration errors.

**Comment by kemeris2000** [comment]
My mistake, there is no such property mentioned in documentation indeed. Just take a note this property works.
