### ISSUE TITLE
Could not find "lowdefy.yaml" file in specified config directory

### ISSUE THREAD

**Issue by retraut** [lowdefy/lowdefy#1658]
#### Describe the bug

`✖ Could not find "lowdefy.yaml" file in specified config directory /private/tmp/project.
`
#### To Reproduce

`pnpx rc init && pnpx lowdefy@rc dev
`
#### Screenshots

<img width="1312" alt="Screenshot 2023-08-12 at 11 27 39 PM" src="https://github.com/lowdefy/lowdefy/assets/3101621/9590d940-0e53-4727-8718-6643556d2279">

#### Lowdefy Version

4.0.0-rc.10

**Comment by retraut** [comment]
https://docs.lowdefy.com/introduction
It seems like a bug in the documentation
`pnpx lowdefy@rc init && pnpx lowdefy@rc dev` - works for me

**Comment by JohannMoller** [comment]
Hi @retraut, thank you for this. It has been fixed in #1660
