### ISSUE TITLE
List as display type, and rename current List to ListInput

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#343]
**Is your feature request related to a problem? Please describe.**
Working with lists require you to mange the list values in state, where all you want to do is display a list of data. 

**Describe the solution you'd like**
List should be a display type with data property, and the current List block should be renamed to ListInput.

**Comment by gitkyle** [comment]
Is there a reason why this was closed as "invalid"? I am trying to do just this, render values in state with display blocks.
