### ISSUE TITLE
Running inside a browser engine

### ISSUE THREAD

**Issue by em3ndez** [lowdefy/lowdefy#536]
I'd like to know if it is possible to deploy a lowdefy application in an Apache webserver. What I mean is if it's possible to run lowdefy inside the javascript engine of a browser (perhaps with certain limitations) instead of inside a Node engine.

**Comment by SamTolmay** [comment]
Hi @em3ndez 

To confirm we are understanding correctly, you would like to host a Lowdefy app as static content, served by an Apache webserver?

We have been thinking about doing this, it would be possible to adapt Lowdefy to build as a static site, but it isn't possible right now.

On a static version of Lowdefy, you wouldn't have any user authentication or authorization, and you wouldn't have any connections/requests/secrets. We would implement a client fetch action, so you would be able to make HTTP requests from the client. Most other things should still be possible.

This is something we would like to build and can prioritise if we have enough requests for this.

I'm converting this to a discussion so we can discuss it there further.

What is your use case for this, and what features would be important to you?
