### ISSUE TITLE
Serializer should handle cyclic object reference.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#569]
**Describe the bug**
When an object is being serialized, [the sterilizer](https://github.com/lowdefy/lowdefy/blob/main/packages/helpers/src/serializer.js) throws for the cyclic object. 

**To Reproduce**
In an AgGrid table try:
```yaml
 valueFormatter:
      _js.function:
        code: |
          function (params) {
            console.info(typeof params)
            return "hello world"
          }
```

**Expected behavior**
Consider a replacer method that can exclude cyclic object references.

**Lowdefy Version**
3.14.1

**Comment by Gervwyk** [comment]
Any someone has any ideas / examples of how to easily detect cyclic object references, that would be helpful. My current thinking is to wrap the initial stringify method in a try-catch then if it fails do a loop over first-level keys in top-level objects and exclude the key that fails. This approach will be slow and does not handle nested cyclic references.

**Comment by ahmedrshdy** [comment]
@Gervwyk it really depneds on what you are tryign to catch so you can avoid swalloing real errors.

For example, if it is about already serialized objects in the object tree then you can use the [replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter) function, to exclude.

another example [here](https://stackoverflow.com/questions/14962018/detecting-and-fixing-circular-references-in-javascript) to capture where the cycle is

**Comment by Gervwyk** [comment]
In v3.16.0 we are replacing the `_js` operator with a version that runs methods as loaded into `window`, thus both the `_js` operator and `JsAction` can now support full browser javascript and does not have to serialize parameters in order to pass variable to a javascript wasm. 

So the reason for which is issue was created is now resolved, however, the serializer still does not catch cyclic object references which should be fine for now. We'll deal with this complexity if it comes up in a different context.
