### ISSUE TITLE
_js.dangerous_eval operator, server side only.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#570]
Consideration for the implications and benefits of a server-side js eval operator as [proposed here](https://github.com/lowdefy/lowdefy/discussions/492#discussioncomment-703087). 

The first question is Should this be an operator?
Please share examples and thoughts around how this can be useful server-side. 

@SamTolmay we should also think of how this can be used in the context of chained requests.

**Comment by SamTolmay** [comment]
Rather implement this as a custom or JavaScript request.
