### ISSUE TITLE
CLI warning creating 404 page

### ISSUE THREAD

**Issue by SamWoolerton** [lowdefy/lowdefy#647]
**Describe the bug**
Running locally in dev mode, the CLI tries to generate a 404 page and adds another `page:` each time, which seems pretty invalid:
```
✖ Error: ENOENT: no such file or directory, mkdir 'C:\programming\fosters\subcontractor-letting\.lowdefy\build\pages\page:page:page:page:page:page:page:page:page:page:page:page:page:page:page:page:page:page:page:page:404'
```

**To Reproduce**
I just went through the tutorial and haven't changed much.

**Expected behavior**
I'd probably expect a 404 page to work out of the box.

**Lowdefy Version**
3.17.2 (latest when I generated the project yesterday)

**Comment by SamTolmay** [comment]
Thanks @SamWoolerton, I will have a look at this.
