### ISSUE TITLE
Divider title is always rendered

### ISSUE THREAD

**Issue by Radiergummi** [lowdefy/lowdefy#790]
#### Describe the bug
Since ~3.20, Divider blocks will render their title slot always, even if no title has been specified.

#### To Reproduce
1. Add a Divider block without a title prop:
   ```yaml
   id: block_id
   type: Divider
   ```

#### Screenshots
<img width="771" alt="Bildschirmfoto 2021-08-24 um 17 43 24" src="https://user-images.githubusercontent.com/6115429/130647732-f7c27670-156e-47da-900b-93ff1d3a5f72.png">

#### Lowdefy Version

Version (or version range) on which you experienced this issue.
`>=3.20`

**Comment by Gervwyk** [comment]
Hi @Radiergummi 

This is caused by the RenderHtml changes in 3.20. Thanks for reporting this. We'll include a fix for the next release.
