### ISSUE TITLE
Version 4 Progress

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#956]
# New features

- App load much faster. The build bundle has been reduced, the data-fetching waterfall has been reduced and blocks are no longer fetched from an external CDN using webpack module federation.
- The V4 server is based on Next.js, which has many advantages and optimizations.
- The Ant Design LESS style variables can be customized. See #893
- Custom plugins make it easier and more standardized to implement custom blocks, connections, actions and operators.
- API routes allow you to write backend APIs, webhooks and data pipelines (Coming soon). See #642
- Statically generated sites (Coming soon). See #639

# Breaking changes

- Multiple contexts on a page are no longer supported. Context category blocks no longer exist, and the first block on a page no longer needs to be of category context.
- The `Context` block no longer has any use, and has been removed. It can be replaced with a `Box`.
- Getter operators can no longer get from another context.
- The _event, _global, _index, _input, _state, and _url_query operators are no longer evaluated in connections or requests. They have been replaced with the `_payload` operator. See #641
- A variety of different icon packages are now supported, thanks to `react-icon`. To use the Ant Design icons from v3, use the icon name as at [react-icons](https://react-icons.github.io/react-icons/).
- Custom blocks using webpack module federation are no longer supported, and are replaced by custom plugins.
- The JsAction Action is replaced by custom plugins.
- The _js operator is replaced by custom plugins.
- Assets from the `public` directory are now served from the root path and not under the public path. (An asset previously served from `https://example.com/public/image.jpg` will now be served from `https://example.com/image.jpg`. This allows for serving files like `favicon.ico`, `sitemap.xml` and `robots.txt`. The assets can be placed in a an additional public folder (`<project-dir>/public/public`) to emulate the previous behavior. 
- The 404 page is now always a public page.
- `Anchor` block schema change, `href` has been removed and now takes the same props as`Link`.
- `_yaml.parse` input string is now passed as `array[0]` or `object.on` instead of simply an input string to allow parsing options to be passed.
- blocks-color-selectors have changed, ColorSelector now only uses react-colorful with a different UX. The following blocks has been removed: ChromeColorSelector, CircleColorSelector, CompactColorSelector, GithubColorSelector, SliderColorSelector, SwatchesColorSelector, TwitterColorSelector.
- `onEnter` and `onEnterAsync` have been removed due to duplicate functionality in `onMount` and `onMountAsync`. Use these instead.
- The color options in `Menu`, `Sider`, `Header`,   have been removed. This impacts color settings for `MobileMenu`, `PageHeaderMenu`, `PageSiderMenu`,  `PageHCF`, `PageHCSF`, `PageHSCF`, `PageSHCF`. Use antd theme less variables instead.
- The `Message` action has been renamed to `DisplayMessage`.

# Currently not working

- [ ] Documentation for version 4.
- [ ] API routes. #642
- [ ] Statically generated sites #639 
- [ ] Deploying with
  - [x] Docker
  - [ ] Netlify
  - [ ] AWS Lambda

# Issues
- [x] #641 
- [x] #883 
- [x] #841 
- [x] #944
- [x] #894 
- [x] #940
- [x] #948
- [x] #920 
- [x] #943
- [x] #893
- [x] #942 
- [x] #977 
- [x] #1005 
- [x] #1046 
- [x] #1048
- [x] #941
- [x] #1049 
- [x] #978 
- [x] #945
- [x] #1103 
- [x] #1104 
- [x] #1106 
- [x] #1102
- [x] #1077
- [x] #1047
- [x] #1086
- [x] #1105 
- [x] #688
- [ ] #1136
- [ ] #946
- [ ] #815 
- [x] #699 
- [x] #639 
- [x] #642

**Comment by Gervwyk** [comment]
🦭
